# Generated by Django 2.2.7 on 2020-03-13 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wechat.Entity')),
                ('image', stdimage.models.StdImageField(default='', upload_to='Activity/image', verbose_name='图片路径')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
            },
            bases=('wechat.entity',),
        ),
        migrations.CreateModel(
            name='AType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='类型')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '活动类型',
                'verbose_name_plural': '活动类型',
            },
        ),
        migrations.CreateModel(
            name='AText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atext', to='activity.Activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动文本',
                'verbose_name_plural': '活动文本',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.AType', verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='activity',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='activity', to='store.Store', verbose_name='活动门店'),
        ),
    ]
