# Generated by Django 2.2.7 on 2020-03-13 09:50

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(default='', upload_to='Product/banner/', verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.CreateModel(
            name='PInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='颜色')),
                ('norms', models.CharField(blank=True, max_length=255, null=True, verbose_name='规格')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='重量')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('image', stdimage.models.StdImageField(blank=True, default='', upload_to='Product/detail/', verbose_name='图片路径')),
                ('quantity', models.IntegerField(blank=True, default=10, verbose_name='虚拟库存')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
            },
        ),
    ]
