# Generated by Django 2.2.7 on 2020-03-13 09:50

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wechat.Entity')),
                ('productId', models.CharField(max_length=100, verbose_name='货号')),
                ('systemCode', models.BigIntegerField(blank=True, null=True, verbose_name='系统编码')),
                ('barCode', models.BigIntegerField(blank=True, null=True, verbose_name='条形编码')),
                ('brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='品牌')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='商品简介')),
                ('image', stdimage.models.StdImageField(blank=True, default='', upload_to='Product/preview/', verbose_name='图片路径')),
                ('shell', models.CharField(choices=[('on', '上架'), ('off', '下架')], default='on', max_length=3, verbose_name='货架')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
            bases=('wechat.entity',),
        ),
        migrations.CreateModel(
            name='PType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类型')),
                ('desc', models.IntegerField(blank=True, choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], null=True, verbose_name='属性')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.PType', verbose_name='父类型')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='PTypePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(default='', upload_to='PType/poster/', verbose_name='图片路径')),
                ('text', models.CharField(default='', max_length=50, verbose_name='配文')),
                ('ptype', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ptposter', to='product.PType', verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '商品类型海报',
                'verbose_name_plural': '商品类型海报',
            },
        ),
        migrations.CreateModel(
            name='PTypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(default='', upload_to='PType/image/', verbose_name='图片路径')),
                ('ptype', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ptimage', to='product.PType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '商品类型图标',
                'verbose_name_plural': '商品类型图标',
            },
        ),
        migrations.CreateModel(
            name='PTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('product', models.ManyToManyField(blank=True, related_name='ptag', to='product.Product', verbose_name='标注商品')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.PType', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='pinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinfo', to='product.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='pbanner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbanner', to='product.Product', verbose_name='商品'),
        ),
    ]
