# Generated by Django 2.2.7 on 2020-03-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wechat.Entity')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='所在商区')),
                ('longlat', models.CharField(blank=True, max_length=100, null=True, verbose_name='经纬度')),
            ],
            options={
                'verbose_name': '门店信息',
                'verbose_name_plural': '门店信息',
            },
            bases=('wechat.entity',),
        ),
    ]
