# Generated by Django 2.2.7 on 2020-03-13 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=256, verbose_name='详细地址')),
                ('is_default', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='默认设置')),
            ],
            options={
                'verbose_name': '收件地址',
                'verbose_name_plural': '收件地址',
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(default='', upload_to='Advert', verbose_name='图片路径')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('is_show', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '首页广告',
                'verbose_name_plural': '首页广告',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('type', models.IntegerField(choices=[(1, '商品'), (2, '门店'), (3, '活动')], verbose_name='类型')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '实体信息',
                'verbose_name_plural': '实体信息',
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='参与者姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='参与者电话')),
            ],
            options={
                'verbose_name': '报名信息',
                'verbose_name_plural': '报名信息',
            },
        ),
        migrations.CreateModel(
            name='Trolly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=1, verbose_name='加购数量')),
                ('checkbox', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否选择')),
                ('pinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trolly', to='product.PInfo', verbose_name='加购商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trolly', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
