# Generated by Django 2.2.7 on 2020-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, '后台'), (1, '小程序')], default=0, verbose_name='类型'),
        ),
    ]
