# Generated by Django 2.2.7 on 2020-03-13 19:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWechat',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unionid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户唯一标识')),
                ('nickName', models.CharField(max_length=20, verbose_name='昵称')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('avatarUrl', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='头像路径')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='所在国家')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='所在城市')),
                ('language', models.CharField(blank=True, max_length=64, verbose_name='语言')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            bases=('user.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
